### ISSUE TITLE
Issue with Test-TargetResource.

### ISSUE THREAD

**Issue by juriskrumins** [PlagueHO/cDFS#3]
When I try to configure DFS using cDFS module I've hit the following issue:

	Cannot bind argument to parameter 'DifferenceObject' because it is null.
	+ CategoryInfo : InvalidData: (:) [], CimException
	+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObjectCommand
	+ PSComputerName : localhost
	VERBOSE: [WEB1]: LCM: [ End Test ] [[cDFSRepGroup]cDFSRepGroup0] in 20.4370 seconds.
	The PowerShell DSC resource BMD_cDFSRepGroup threw one or more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW
	channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
	+ CategoryInfo : InvalidOperation: (:) [], CimException
	+ FullyQualifiedErrorId : NonTerminatingErrorFromProvider
	+ PSComputerName : localhost

This comes from the following par of the code inside of Test-TargetResource function:

		$ExistingFolders = (Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName
            if ((Compare-Object `
                -ReferenceObject $Folders `
                -DifferenceObject $ExistingFolders).Count -ne 0) {

I believe it's necessary to change it to the following one:

            $ExistingFolders = (Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName
            if($ExistingFolders -eq $null)
            {
                $ExistingFolders=@()
            }
            if ((Compare-Object `
                -ReferenceObject $Folders `
                -DifferenceObject $ExistingFolders).Count -ne 0) {

**Comment by PlagueHO** [comment]
That's a good catch. I'm embarrassed to say I've made this mistake before. Another way of fixing it is to explicitly cast the $ExistingFolders variable to an array:
E.g.
```powershell
    $ExistingFolders = (Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName
        if ((Compare-Object `
            -ReferenceObject $Folders `
            -DifferenceObject $ExistingFolders).Count -ne 0) {
```
Wrap the whole assignment in a @()
```powershell
    $ExistingFolders = @((Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName)
        if ((Compare-Object `
            -ReferenceObject $Folders `
            -DifferenceObject $ExistingFolders).Count -ne 0) {
```

I'll get it done now and release it.

Integration tests should have picked this up but I haven't had a chance to write them yet -they're on my todo list. Thanks again.

**Comment by PlagueHO** [comment]
I've released the update for this on PowerShellGallery and it's available here. Please let me know if this doesn't fix the issue for you.

Thanks again and sorry about the bug!

**Comment by juriskrumins** [comment]
Works for me. Thanks.

**Comment by PlagueHO** [comment]
Awesome! :+1: Thanks for your help!
